-- CreateTable
CREATE TABLE "points" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "startR" INTEGER NOT NULL,
    "startC" INTEGER NOT NULL,
    "endR" INTEGER NOT NULL,
    "endC" INTEGER NOT NULL
);
